# Generated by Django 2.1.15 on 2025-02-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baladeaah', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonForm',
            new_name='PersonlyForm',
        ),
        migrations.AlterModelTable(
            name='personlyform',
            table='personly',
        ),
    ]
