# Generated by Django 2.1.15 on 2025-02-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baladeaah', '0002_auto_20250214_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('degree', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'Man',
            },
        ),
        migrations.DeleteModel(
            name='PersonlyForm',
        ),
    ]
