# Generated by Django 2.1.15 on 2025-02-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baladeaah', '0003_auto_20250214_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManForm',
        ),
    ]
