# Generated by Django 2.1.15 on 2025-02-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baladeaah', '0005_stu'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'school',
            },
        ),
    ]
