# Generated by Django 2.1.15 on 2025-02-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baladeaah', '0006_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='file',
            field=models.ImageField(upload_to='photo/%y/%m/%d'),
        ),
    ]
