# Generated by Django 2.1.15 on 2025-02-15 20:21

import baladeaah.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baladeaah', '0008_auto_20250215_2229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stu',
        ),
        migrations.AlterField(
            model_name='school',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=baladeaah.models.filepath),
        ),
    ]
