# Generated by Django 2.1.15 on 2025-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baladeaah', '0009_auto_20250215_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='video',
            field=models.FileField(default='photo/25', upload_to='photo/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='school',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d'),
        ),
    ]
